### ISSUE TITLE
Feature Request - Remember State

### ISSUE THREAD

**Issue by kellishaver** [jonathanstark/jbot-for-trello#1]
Maybe we can do something with localStorage to remember the state of the page, so that if you're zoomed in to a list and leave/close the tab, the next time you navigate back to the board, it automatically zooms to the list you were looking at.

**Comment by jonathanstark** [comment]
I thought about localStorage but it doesn't work in porn mode. Is that a big deal?

**Comment by kellishaver** [comment]
I don't think so. Personally, I don't use Trello for porn much.

**Comment by jonathanstark** [comment]
HAHA!

**Comment by jonathanstark** [comment]
Done
